openapi: 3.0.0
info:
  description: ''
  title: Certificate Of Origin
  version: ''
servers: []
paths: {}
components:
  schemas:
    CertificateOfOrigin:
      type: object
      properties:
        originCountry:
          description: missing description
          type: string
          enum:
            - DK
            - SE
            - 'NO'
            - US
        destinationCountry:
          description: missing description
          type: string
          enum:
            - DK
            - SE
            - 'NO'
            - US
        transportEquipment:
          $ref: '#/components/schemas/TransportEquipment'
    Seal:
      type: object
      properties:
        type:
          description: missing description
          type: string
        value:
          description: missing description
          type: string
    TransportEquipment:
      type: object
      properties:
        equipmentNumber:
          description: Container number.
          type: string
        equipmentType:
          description: ISO 6346 size and type code (for example "45G1")
          type: string
        printedEquipmentType:
          description: >-
            The container size and type, as printed on the transport document
            (for example "40 DRY 9''6").
          type: string
        seals:
          items:
            $ref: '#/components/schemas/Seal'
          type: array
