openapi: 3.0.0
info:
  description: ''
  title: Bill Of Lading
  version: ''
servers: []
paths: {}
components:
  schemas:
    Address:
      type: object
      properties:
        street:
          description: missing description
          type: string
        city:
          description: missing description
          type: string
        state:
          description: missing description
          type: string
        country:
          description: missing description
          type: string
    BillOfLading:
      type: object
      properties:
        negotiable:
          description: missing description
          type: string
        dateOfAcceptance:
          description: missing description
          type: string
        freightedAtAd:
          description: missing description
          type: string
        certifiedMember:
          description: missing description
          type: string
        declarationOfInterest:
          description: Consignor''s declaration of interest in timely delivery of goods.
          type: string
        shippedOnBoardDate:
          description: missing description
          type: string
        consignee:
          $ref: '#/components/schemas/Consignee'
        consignor:
          $ref: '#/components/schemas/Consignor'
        otherParties:
          items:
            $ref: '#/components/schemas/OtherParty'
          type: array
        notifyParties:
          items:
            $ref: '#/components/schemas/NotifyParty'
          type: array
        references:
          items:
            $ref: '#/components/schemas/Reference'
          type: array
        placeOfReceipt:
          $ref: '#/components/schemas/Location'
        placeOfDelivery:
          $ref: '#/components/schemas/Location'
        consignmentItems:
          items:
            $ref: '#/components/schemas/ConsignmentItem'
          type: array
          minItems: 1
        placeOfIssance:
          $ref: '#/components/schemas/Location'
        consignment:
          items:
            $ref: '#/components/schemas/Consignment'
          type: array
          minItems: 1
        carrier:
          $ref: '#/components/schemas/Carrier'
        document:
          $ref: '#/components/schemas/Document'
        portOfLoading:
          $ref: '#/components/schemas/Location'
        portOfDischarge:
          $ref: '#/components/schemas/Location'
    Carrier:
      type: object
      properties:
        SCAC:
          description: missing description
          type: string
        name:
          description: missing description
          type: string
        placeOfBusiness:
          items:
            description: missing description
            type: string
          type: array
      required:
        - name
    Charges:
      type: object
      properties:
        chargeType:
          description: missing description
          type: string
        rate:
          description: missing description
          type: string
        per:
          description: missing description
          type: string
        currency:
          description: missing description
          type: string
        paymentTerm:
          description: missing description
          type: string
          enum:
            - prepaid
            - collect
        amount:
          description: missing description
          type: string
        freightPayableAt:
          description: missing description
          type: string
        invoiceParty:
          description: missing description
          type: string
    CommunicationDetails:
      type: object
      properties:
        telephone:
          description: missing description
          type: string
        fax:
          description: missing description
          type: string
        email:
          description: missing description
          type: string
    Consignee:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Consignment:
      type: object
      properties:
        billOfLadingNumber:
          description: missing description
          type: string
        bookingNumber:
          description: missing description
          type: string
        transportMeans:
          items:
            $ref: '#/components/schemas/TransportMeans'
          type: array
        charges:
          items:
            $ref: '#/components/schemas/Charges'
          type: array
        tes:
          $ref: '#/components/schemas/TransportEquipment'
    ConsignmentItem:
      type: object
      properties:
        sequenceId:
          description: missing description
          type: string
        numberAndKindOfPackages:
          $ref: '#/components/schemas/NumberAndKindOfPackages'
        weight:
          $ref: '#/components/schemas/Weight'
        measurements:
          $ref: '#/components/schemas/Meassurement'
        transportEquipment:
          items:
            $ref: '#/components/schemas/TransportEquipment'
          type: array
    Consignor:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Document:
      type: object
      properties:
        originatorName:
          description: missing description
          type: string
        originatorId:
          description: missing description
          type: string
        dateOfIssuance:
          description: missing description
          type: string
    Location:
      type: object
      properties:
        name:
          description: missing description
          type: string
        UNLocode:
          description: missing description
          type: string
        printedLocation:
          description: missing description
          type: string
    MarksAndNumbers:
      type: object
      properties:
        shippingMarks:
          description: missing description
          type: string
    Meassurement:
      type: object
      properties:
        value:
          description: missing description
          type: string
        unit:
          description: missing description
          type: string
          enum:
            - cm
            - cf
    NotifyParty:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    NumberAndKindOfPackages:
      type: object
      properties:
        numberOfPackages:
          description: missing description
          type: string
        typeOfPackages:
          description: missing description
          type: string
        goodsItemDescription:
          description: missing description
          type: string
        marksAndNumbers:
          items:
            $ref: '#/components/schemas/MarksAndNumbers'
          type: array
    OtherParty:
      type: object
      properties:
        partyType:
          description: missing description
          type: string
          enum:
            - Exporter
            - Importer
            - Origin 3PL
            - Destination 3PL
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Party:
      type: object
      properties:
        name:
          description: missing description
          type: string
        printedParty:
          description: missing description
          type: string
        registeredForVAT:
          description: missing description
          type: string
        taxReference:
          description: missing description
          type: string
        partyRef:
          description: missing description
          type: string
        organizationId:
          description: missing description
          type: string
        address:
          $ref: '#/components/schemas/Address'
        communicationDetails:
          $ref: '#/components/schemas/CommunicationDetails'
    Reference:
      type: object
      properties:
        type:
          description: missing description
          type: string
        value:
          description: missing description
          type: string
    Seal:
      type: object
      properties:
        type:
          description: missing description
          type: string
        value:
          description: missing description
          type: string
    TransportEquipment:
      type: object
      properties:
        equipmentNumber:
          description: missing description
          type: string
        equipmentType:
          description: ISO 6346 size and type code (for example "45G1")
          type: string
        printedEquipmentType:
          description: >-
            The container size and type, as printed on the transport document
            (for example "40 DRY 9''6").
          type: string
        seals:
          items:
            $ref: '#/components/schemas/Seal'
          type: array
    TransportMeans:
      type: object
      properties:
        IMOCode:
          description: missing description
          type: string
        name:
          description: missing description
          type: string
        transportMovement:
          $ref: '#/components/schemas/TransportMovement'
    TransportMovement:
      type: object
      properties:
        voyageId:
          description: missing description
          type: string
    Weight:
      type: object
      properties:
        value:
          description: missing description
          type: string
        unit:
          description: missing description
          type: string
          enum:
            - kgs
            - lbs
